user nginx;
worker_processes auto;

events {
    worker_connections 1024;
}

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    server {
        listen 1313;
        server_name localhost;

        location / {
            root /home/static;
            index index.html index.htm;
            # Add rules like this
            # if ($query_string = "p=2") {
            #    return 302 /about/;
            # }
            
            if ($query_string = "page_id=3") { return 302 /; }
            if ($query_string = "p=3319") { return 302 /buy-this-not-that-budget-friendly-tools-for-beginner-bike-mechanics/; }
            if ($query_string = "p=3420") { return 302 /diy-bike-maintenance/; }
            if ($query_string = "p=3434") { return 302 /shimano-dura-ace-vs-ultegra-r8100-is-the-weight-savings-worth-the-cost/; }
            if ($query_string = "p=3448") { return 302 /new-sram-eagle-70-and-90-vs-shimano-slx-xt-xtr-full-drivetrain-comparison-with-weight-and-price/; }
            if ($query_string = "p=3461") { return 302 /beginner-bike-repair-tools/; }
            if ($query_string = "p=3538") { return 302 /hardtail-gravel-bike-dropbar-conversion/; }
            if ($query_string = "p=3293") { return 302 /weigh-in-2023-cannondale-habit-frameset-weight/; }
            if ($query_string = "p=3310") { return 302 /5-road-bike-saddle-bag-essentials-for-tubeless-road-bikes/; }
            if ($query_string = "p=3328") { return 302 /weigh-in-2022-fox-36-grip-2-29-150mm-travel/; }
            if ($query_string = "p=3425") { return 302 /transferable-warranties/; }
            if ($query_string = "p=3456") { return 302 /how-i-set-up-my-specialized-stumpjumper-evo-alloy-mullet-custom-trail-bike-build/; }
            if ($query_string = "p=3486") { return 302 /; }
            if ($query_string = "p=3519") { return 302 /hardtail-gravel-bike-conversion/; }
            if ($query_string = "p=3526") { return 302 /how-to-plan-a-mountain-bike-frame-swap/; }
            if ($query_string = "p=3380") { return 302 /make-extra-money-selling-bike-parts-on-ebay-fees-tips-explained/; }
            if ($query_string = "p=3398") { return 302 /feb-deals/; }
            if ($query_string = "p=3406") { return 302 /2025-cannondale-superx-review/; }
            if ($query_string = "p=3491") { return 302 /balance-bike-vs-training-wheels-2-year-old/; }
            if ($query_string = "p=3497") { return 302 /https-mizubikes-com-specialized-aethos-review/; }
            if ($query_string = "p=3322") { return 302 /cannondale-caad-13-is-aluminum-still-a-good-value-vs-the-carbon-2023-supersix-evo-hi-mod/; }
            if ($query_string = "p=3325") { return 302 /best-options-for-a-1-year-old-baby-a-bike-trailer-or-a-bike-baby-seat/; }
            if ($query_string = "p=3438") { return 302 /unboxing-the-2025-specialized-stumpjumper-15-alloy-is-this-the-best-trail-frame-deal-right-now/; }
            if ($query_string = "p=3479") { return 302 /2025-specialized-turbo-levo-4-lineup-guide/; }
            if ($query_string = "p=3543") { return 302 /intermediate-bike-tools/; }
        }
    }
}
